# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f27b3b32b550cb51956e22705084052d2618ed925afc1dd239cb64742d3cb19e67dc0fa40d5dc2fe4dc094ff8ce2294f3f23a30f457717ce9e274b57d6d42c97

test:
  secret_key_base: 0c377e947a7131048020c96023107f8e5a01421b25b1e775aff6b98072473abf3e9815ef5e93e7f94b2a1795c7ad87aa9b77ff8b5baaa634f74aae8503b2712c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
