# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c67238993b90f2d1146190f23504f8e4e3b432039b9a5456aa80b9fc58ec762855882ea00033dfc4727fd46cbd1a6d76975372fbc2aa0a9d2fabe9fc11638074

test:
  secret_key_base: 9ed84d65f3db6be8765a08632d450d158aabcf72c1b7a5d9cc935d07ae48191ec8da5c26ff72e541e74809cf69a8fed295d9b5c62a7d4439cea171ac0e663a88

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
